### ISSUE TITLE
francois reported problem with deleting configuration

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/python-eduvpn-client#14]
```
INFO:main:deleting provider config
INFO:eduvpn.providers.nm:deleting profile with name demo.eduvpn.nl using NetworkManager
INFO:main:a configuration was selected
Traceback (most recent call last):
  File "/usr/bin/eduvpn-client", line 176, in delete
    self.update_providers()
  File "/usr/bin/eduvpn-client", line 70, in update_providers
    for provider in list_providers():
  File "/usr/lib/python2.7/dist-packages/eduvpn/providers/nm.py", line 55, in list_providers
    vpn_connections = [c.GetSettings()['connection']['id'] for c in all_connections if c.GetSettings()['connection']['type'] == 'vpn']
  File "/usr/lib/python2.7/dist-packages/NetworkManager.py", line 115, in proxy_call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in call
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.NetworkManager.Settings.Connection' on object at path /org/freedesktop/NetworkManager/Settings/3
```

**Comment by gijzelaerr** [comment]
this is probably because the delete action didnt update the interface and a double delete was triggered
