### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fkooman** [gijzelaerr/python-eduvpn-client#2]
```
INFO:__main__:calling callback
INFO:eduvpn.remote:Retrieving profile list from https://demo.eduvpn.nl/portal/api.php
INFO:__main__:thread running in background
INFO:eduvpn.remote:Creating and retrieving key pair from https://demo.eduvpn.nl/portal/api.php
INFO:eduvpn.remote:Retrieving profile config from https://demo.eduvpn.nl/portal/api.php
Traceback (most recent call last):
  File "/home/fkooman/Projects/eduvpn-linux-client/scripts/eduvpn-client", line 103, in profile_selected
    makedirs(path.dirname(parent))
  File "/home/fkooman/Projects/eduvpn-linux-client/.v/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/fkooman/.config'
```

This last line is also quite disturbing?

**Comment by gijzelaerr** [comment]
looks like you are not running the latest release?

**Comment by gijzelaerr** [comment]
looks like it is old unreleased code from master, not an issue at the moment anymore.
